parameters:
    fidesio_sonata_admin_jms_translation.updater.class: Fidesio\SonataAdminJMSTranslationBundle\Translation\Updater

services:
     fidesio_sonata_admin_jms_translation.updater:
        class: %fidesio_sonata_admin_jms_translation.updater.class%
        arguments:
            - @jms_translation.loader_manager
            - @jms_translation.extractor_manager
            - @logger
            - @jms_translation.file_writer